services:
  st_app:
    image: jackspicer/metallographic-image-analysis:latest
    command: poetry run streamlit run st_app.py

    ports:
      - "8501:8501"

  st-app-dev:
    build: .
    command: poetry run streamlit run st_app.py

    ports:
      - "8502:8501"
